//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLinkGui.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyLinkGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;result&quot;:{&quot;map&quot;:{&quot;15_16868_11195_0_8_100&quot;:{&quot;error&quot;:&quot;TIMEOUT&quot;},&quot;15_16868_11198_0_8_100&quot;:{&quot;error&quot;:&quot;TIMEOUT&quot;},&quot;15_16874_11198_0_8_100&quot;:{&quot;error&quot;:&quot;TIMEOUT&quot;},&quot;15_16875_11198_0_8_100&quot;:{&quot;error&quot;:&quot;TIMEOUT&quot;},&quot;15_16869_11197_0_8_100&quot;:{&quot;error&quot;:&quot;TIMEOUT&quot;},&quot;15_16869_11196_0_8_100&quot;:{&quot;gameEntities&quot;:[[&quot;1dd7056a4b5649d9979bcd307ffb1048.9&quot;,1550318690742,[&quot;e&quot;,&quot;E&quot;,&quot;8de69bcf79334cf293a95db911b4cc95.16&quot;,47414925,9741203,&quot;f8c47435042b4c349c125d58e740da73.16&quot;,47452186,9879455]],[&quot;2881a6cca69d491b86fbce4b85f787cc.9&quot;,1550132625030,[&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string testEntityResponse {
            get {
                return ResourceManager.GetString("testEntityResponse", resourceCulture);
            }
        }
    }
}
